### ISSUE TITLE
Cura 4.0 crashes with the awesome resource

### ISSUE THREAD

**Issue by ieelan** [trouch/CreawsomeMod#15]
I replaced (added the new) resource folder and restarted cura 4.0 but it crashes.  Any suggestions to correct.  When I return the old (original) resource folder, cura 4.0 starts up.

**Comment by jessearmstrong** [comment]
I have the same issue

**Comment by jessearmstrong** [comment]
Here's the crash data that I get when trying to start with mod installed.

`Process:               cura [2853]
Path:                  /Applications/Ultimaker Cura.app/Contents/MacOS/cura
Identifier:            nl.ultimaker.cura
Version:               4.0 (4.0.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           cura [2853]
User ID:               501

Date/Time:             2019-05-24 08:27:39.797 -0500
OS Version:            Mac OS X 10.14.5 (18F132)
Report Version:        12
Anonymous UUID:        A66EF818-F292-F884-0126-10689FB00D77


Time Awake Since Boot: 62000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld2 mode
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff76b622c6 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff76c1dbf1 pthread_kill + 284
2   libsystem_c.dylib             	0x00007fff76acc6a6 abort + 127
3   nl.ultimaker.cura             	0x000000010b88359e Py_FatalError + 462
4   nl.ultimaker.cura             	0x000000010b883378 _Py_InitializeEx_Private + 1336
5   nl.ultimaker.cura             	0x000000010b78aed7 main + 791
6   libdyld.dylib                 	0x00007fff76a273d5 start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000000011b3b75c0  rcx: 0x00007ffee44754e8  rdx: 0x0000000000000000
  rdi: 0x0000000000000307  rsi: 0x0000000000000006  rbp: 0x00007ffee4475520  rsp: 0x00007ffee44754e8
   r8: 0x000000010b7afe10   r9: 0x00007fa894403310  r10: 0x0000000000000000  r11: 0x0000000000000206
  r12: 0x0000000000000307  r13: 0x000000010b9b2be8  r14: 0x0000000000000006  r15: 0x000000000000002d
  rip: 0x00007fff76b622c6  rfl: 0x0000000000000206  cr2: 0x00007fffad38d188
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133


Binary Images:
       0x10b78a000 -        0x10b931ff7 +nl.ultimaker.cura (4.0 - 4.0.0) <4E5DFBFF-A1A4-3774-837B-716108BF2954> /Applications/Ultimaker Cura.app/Contents/MacOS/cura
       0x11b315000 -        0x11b37f6ef  dyld (655.1.1) <CE635DB2-D47E-3C05-A0A3-6BD982E7E750> /usr/lib/dyld
    0x7fff4aac2000 -     0x7fff4af06fff  com.apple.CoreFoundation (6.9 - 1575.12) <64C38BF2-1869-33C8-B1B6-DCA9C824C0E4> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff735cf000 -     0x7fff735d0ffb  libDiagnosticMessagesClient.dylib (107) <A14D0819-0970-34CD-8680-80E4D7FE8C2C> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff73a0e000 -     0x7fff73a0fffb  libSystem.B.dylib (1252.250.1) <1A13E822-B59C-3A36-A2E4-9968149714F9> /usr/lib/libSystem.B.dylib
    0x7fff73c51000 -     0x7fff73ca4ff7  libc++.1.dylib (400.9.4) <9A60A190-6C34-339F-BB3D-AACE942009A4> /usr/lib/libc++.1.dylib
    0x7fff73ca5000 -     0x7fff73cbaff7  libc++abi.dylib (400.17) <38C09CED-9090-3719-90F3-04A2749F5428> /usr/lib/libc++abi.dylib
    0x7fff74701000 -     0x7fff74962fff  libicucore.A.dylib (62135.0.1) <2B292561-798A-381C-AA41-90EE6549C7CF> /usr/lib/libicucore.A.dylib
    0x7fff75245000 -     0x7fff759cafdf  libobjc.A.dylib (756.2) <7C312627-43CB-3234-9324-4DEA92D59F50> /usr/lib/libobjc.A.dylib
    0x7fff760b4000 -     0x7fff760c6ff7  libz.1.dylib (70.200.4) <B048FC1F-058F-3A08-A1FE-81D5308CB3E6> /usr/lib/libz.1.dylib
    0x7fff768aa000 -     0x7fff768aeff3  libcache.dylib (81) <1987D1E1-DB11-3291-B12A-EBD55848E02D> /usr/lib/system/libcache.dylib
    0x7fff768af000 -     0x7fff768b9ff3  libcommonCrypto.dylib (60118.250.2) <1765BB6E-6784-3653-B16B-CB839721DC9A> /usr/lib/system/libcommonCrypto.dylib
    0x7fff768ba000 -     0x7fff768c1ff7  libcompiler_rt.dylib (63.4) <5212BA7B-B7EA-37B4-AF6E-AC4F507EDFB8> /usr/lib/system/libcompiler_rt.dylib
    0x7fff768c2000 -     0x7fff768cbff7  libcopyfile.dylib (146.250.1) <98CD00CD-9B91-3B5C-A9DB-842638050FA8> /usr/lib/system/libcopyfile.dylib
    0x7fff768cc000 -     0x7fff76950fc3  libcorecrypto.dylib (602.260.2) <BED0F385-D8A2-334A-BD7B-0673B5DABBC5> /usr/lib/system/libcorecrypto.dylib
    0x7fff769d7000 -     0x7fff76a10ff7  libdispatch.dylib (1008.250.7) <26DF5B1E-A388-38EF-B73B-AF0E93FB02DB> /usr/lib/system/libdispatch.dylib
    0x7fff76a11000 -     0x7fff76a3dff7  libdyld.dylib (655.1.1) <002418CC-AD11-3D10-865B-015591D24E6C> /usr/lib/system/libdyld.dylib
    0x7fff76a3e000 -     0x7fff76a3effb  libkeymgr.dylib (30) <0D0F9CA2-8D5A-3273-8723-59987B5827F2> /usr/lib/system/libkeymgr.dylib
    0x7fff76a4c000 -     0x7fff76a4cff7  liblaunch.dylib (1336.261.2) <BD5CDB35-2BB4-349A-8D14-78E387563F89> /usr/lib/system/liblaunch.dylib
    0x7fff76a4d000 -     0x7fff76a52fff  libmacho.dylib (927.0.2) <3C5C9024-45FD-38C2-B01A-07A322966063> /usr/lib/system/libmacho.dylib
    0x7fff76a53000 -     0x7fff76a55ffb  libquarantine.dylib (86.220.1) <6D0BC770-7348-3608-9254-F7FFBD347634> /usr/lib/system/libquarantine.dylib
    0x7fff76a56000 -     0x7fff76a57ff7  libremovefile.dylib (45.200.2) <9FBEB2FF-EEBE-31BC-BCFC-C71F8D0E99B6> /usr/lib/system/libremovefile.dylib
    0x7fff76a58000 -     0x7fff76a6fff3  libsystem_asl.dylib (356.200.4) <A62A7249-38B8-33FA-9875-F1852590796C> /usr/lib/system/libsystem_asl.dylib
    0x7fff76a70000 -     0x7fff76a70ff7  libsystem_blocks.dylib (73) <A453E8EE-860D-3CED-B5DC-BE54E9DB4348> /usr/lib/system/libsystem_blocks.dylib
    0x7fff76a71000 -     0x7fff76af8fff  libsystem_c.dylib (1272.250.1) <7EDACF78-2FA3-35B8-B051-D70475A35117> /usr/lib/system/libsystem_c.dylib
    0x7fff76af9000 -     0x7fff76afcffb  libsystem_configuration.dylib (963.260.1) <C7D2BA09-8D5B-3393-8D84-304D76C55DEF> /usr/lib/system/libsystem_configuration.dylib
    0x7fff76afd000 -     0x7fff76b00ff7  libsystem_coreservices.dylib (66) <719F75A4-74C5-3BA6-A09E-0C5A3E5889D7> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff76b01000 -     0x7fff76b07fff  libsystem_darwin.dylib (1272.250.1) <EC9B39A5-9592-3577-8997-7DC721D20D8C> /usr/lib/system/libsystem_darwin.dylib
    0x7fff76b08000 -     0x7fff76b0eff7  libsystem_dnssd.dylib (878.260.1) <64B79B01-B1B0-3C7E-87A1-023B71843F1F> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff76b0f000 -     0x7fff76b5affb  libsystem_info.dylib (517.200.9) <D09D5AE0-2FDC-3A6D-93EC-729F931B1457> /usr/lib/system/libsystem_info.dylib
    0x7fff76b5b000 -     0x7fff76b83ff7  libsystem_kernel.dylib (4903.261.4) <7B0F52C4-4CC9-3282-8457-C18C6FE1B99E> /usr/lib/system/libsystem_kernel.dylib
    0x7fff76b84000 -     0x7fff76bcfff7  libsystem_m.dylib (3158.200.7) <F19B6DB7-014F-3820-831F-389CCDA06EF6> /usr/lib/system/libsystem_m.dylib
    0x7fff76bd0000 -     0x7fff76bfafff  libsystem_malloc.dylib (166.261.1) <4D1CEF38-DE32-3ECF-9F70-0ADDD5C8775F> /usr/lib/system/libsystem_malloc.dylib
    0x7fff76bfb000 -     0x7fff76c05ff7  libsystem_networkextension.dylib (767.250.2) <FF06F13A-AEFE-3A27-A073-910EF78AEA36> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff76c06000 -     0x7fff76c0dfff  libsystem_notify.dylib (172.200.21) <145B5CFC-CF73-33CE-BD3D-E8DDE268FFDE> /usr/lib/system/libsystem_notify.dylib
    0x7fff76c0e000 -     0x7fff76c17fef  libsystem_platform.dylib (177.250.1) <16949870-9152-3B0D-9EF0-40FAF84B0F1E> /usr/lib/system/libsystem_platform.dylib
    0x7fff76c18000 -     0x7fff76c22ff7  libsystem_pthread.dylib (330.250.2) <2D5C08FF-484F-3D59-9132-CE1DCB3F76D7> /usr/lib/system/libsystem_pthread.dylib
    0x7fff76c23000 -     0x7fff76c26ff7  libsystem_sandbox.dylib (851.260.2) <9CACC5F5-3859-3A1F-BCC6-96DDD4A556A8> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff76c27000 -     0x7fff76c29ff3  libsystem_secinit.dylib (30.260.2) <88F3CE61-5FAD-3CDA-AA13-B5B18B3EBD26> /usr/lib/system/libsystem_secinit.dylib
    0x7fff76c2a000 -     0x7fff76c31ff3  libsystem_symptoms.dylib (820.267.1) <03F1C2DD-0F5A-3D9D-88F6-B26C0F94EB52> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff76c32000 -     0x7fff76c47fff  libsystem_trace.dylib (906.260.1) <100013AE-0443-3CF0-AC17-5D934608B60B> /usr/lib/system/libsystem_trace.dylib
    0x7fff76c49000 -     0x7fff76c4effb  libunwind.dylib (35.4) <24A97A67-F017-3CFC-B0D0-6BD0224B1336> /usr/lib/system/libunwind.dylib
    0x7fff76c4f000 -     0x7fff76c7efff  libxpc.dylib (1336.261.2) <9A0FFA79-082F-3293-BF49-63976B073B74> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 35380
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=242.6M resident=0K(0%) swapped_out_or_unallocated=242.6M(100%)
Writable regions: Total=657.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=657.4M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Kernel Alloc Once                    8K        1 
MALLOC                           153.1M       13 
MALLOC guard page                   24K        5 
MALLOC_MEDIUM (reserved)         112.0M        1         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
__DATA                            4208K       45 
__LINKEDIT                       222.6M        3 
__TEXT                            20.0M       43 
__UNICODE                          564K        1 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                            960.4M      117 
TOTAL, minus reserved VM space   464.4M      117 

Model: iMac18,3, BootROM 172.0.0.0.0, 4 processors, Intel Core i7, 4.2 GHz, 40 GB, SMC 2.41f1
Graphics: kHW_AMDRadeonPro580Item, Radeon Pro 580, spdisplays_pcie_device, 8 GB
Memory Module: BANK 0/DIMM0, 16 GB, DDR4, 2400 MHz, 0x802C, 0x313641544632473634485A2D3247334131202020
Memory Module: BANK 0/DIMM1, 4 GB, DDR4, 2400 MHz, 0x802C, 0x344154463531323634485A2D3247334232202020
Memory Module: BANK 1/DIMM0, 16 GB, DDR4, 2400 MHz, 0x802C, 0x313641544632473634485A2D3247334131202020
Memory Module: BANK 1/DIMM1, 4 GB, DDR4, 2400 MHz, 0x802C, 0x344154463531323634485A2D3247334232202020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x16F), Broadcom BCM43xx 1.0 (7.77.61.2 AirPortDriverBrcmNIC-1305.8)
Bluetooth: Version 6.0.12f1, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Wi-Fi, AirPort, en1
PCI Card: Apple 57761-B0, Ethernet Controller, Thunderbolt@131,0,0
PCI Card: pci11c1,5901, IEEE 1394 Open HCI, Thunderbolt@130,0,0
PCI Card: pci12d8,400e, USB Open Host Controller, Thunderbolt@129,0,0
PCI Card: pci12d8,400e, USB Open Host Controller, Thunderbolt@129,0,1
PCI Card: pci12d8,400f, USB Enhanced Host Controller, Thunderbolt@129,0,2
PCI Card: Apple 57761-B0, Ethernet Controller, Thunderbolt@137,0,0
PCI Card: pci11c1,5901, IEEE 1394 Open HCI, Thunderbolt@136,0,0
PCI Card: pci12d8,400e, USB Open Host Controller, Thunderbolt@140,0,0
PCI Card: pci12d8,400e, USB Open Host Controller, Thunderbolt@140,0,1
PCI Card: pci12d8,400f, USB Enhanced Host Controller, Thunderbolt@140,0,2
USB Device: USB 3.0 Bus
USB Device: Expansion
USB Device: USB3.0 Hub
USB Device: USB Storage
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB2.0 Hub
USB Device: Magic Trackpad 2
USB Device: USB3.0 Card Reader
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Display)
USB Device: Apple Thunderbolt Display
USB Device: Display Audio
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Display)
USB Device: Apple Thunderbolt Display
USB Device: Display Audio
Thunderbolt Bus: iMac, Apple Inc., 41.1
Thunderbolt Device: Thunderbolt Display, Apple Inc., 1, 26.2
`

**Comment by Davinci522** [comment]
There is a secondary resources folder (lowercase) inside the first Resources folder (uppercase) you see. You need to replace the secondary lowercase one, not the first uppercase one. I had the same issue till I compared what folders were in them.

**Comment by jessearmstrong** [comment]
That did the trick! Thank you!

**Comment by trouch** [comment]
thanks @Davinci522
