### ISSUE TITLE
Store the flow rate in the material profile

### ISSUE THREAD

**Issue by zebons** [trouch/CreawsomeMod#30]
In the same maner that temperature, retracts parameters, flow'd be managed in the material profile.
If possible add the flow parameter in the material's profile.

**Comment by BoatrightTBC** [comment]
Couldn't agree more. I have some filaments which hate to be rushed, and even with my microswiss all metal hot end, just won't go as fast as others. I would love to be able to adjust flow on a material by material basis.

**Comment by Ghostkeeper** [comment]
It's not used very often, but Cura's material profiles can store a value for flow by using the `cura` namespace like so:

    <cura:setting key="material_flow">40</cura:setting>

Here's an example of a material profile that uses this type of setting key: https://github.com/Ghostkeeper/3D4MakersFacilianC8/blob/master/3d4makers_facilan_c8.xml.fdm_material

**Comment by rlogiacco** [comment]
@Ghostkeeper do you scavenge the existing materials or is there a list of those keys published somewhere? All my searches have failed so far...

**Comment by stelgenhof** [comment]
@Ghostkeeper Cura keeps these settings (flow) in the general cura.cfg file. What is the rationale for that? To me material flow seems an attribute of the filament and would think it belongs to the material settings. The same thing is the case for material price. (Just curious :) )

**Comment by Ghostkeeper** [comment]
> @Ghostkeeper do you scavenge the existing materials or is there a list of those keys published somewhere? All my searches have failed so far...

The list of keys supported in normal `<setting>` tags is here: https://github.com/Ultimaker/Cura/blob/f6627daa49ecde38df115a88c8bfc61c834518e8/plugins/XmlMaterialProfile/XmlMaterialProfile.py#L1171

The list of settings supported in `<cura:setting>` tags (is actually all Cura settings) is here: https://github.com/Ultimaker/Cura/blob/master/resources/definitions/fdmprinter.def.json

> @Ghostkeeper Cura keeps these settings (flow) in the general cura.cfg file. What is the rationale for that? To me material flow seems an attribute of the filament and would think it belongs to the material settings. The same thing is the case for material price. (Just curious :) )

I actually think that material flow is more of an attribute of the feeder on your printer rather than of the filament, though in reality it's probably a combination. And of course you also need to take into account the quality profile, because with higher layer heights you're going to extrude faster and then you'll have more slip as well.

The point I'm trying to make is that if you look closely enough, almost every setting is influenced by multiple components in the setting stack. That's why Cura doesn't make any assumptions and doesn't restrict certain settings to certain points in the setting stack. Restricting it would only make it harder on the profile developers and harder on the code complexity.

**Comment by stelgenhof** [comment]
@Ghostkeeper Thanks for the explanation! I also agree it is a combination: there are multiple parameters that can be used to manage the material flow. Just wondering because other slicers (e.g. Slic3r) have this defined as an attribute of the filament.

**Comment by zebons** [comment]
@Ghostkeeper I tried your solution (Cura 4.0 & Cura 4.1) to store Cura namespace parameter in a material profile but it dis'n' seem to work :

**Comment by trouch** [comment]
thanks a lot @Ghostkeeper for pointing those informations out !
Cura wiki lack a bit of info and I haven't dig into all the source code yet.

**Comment by Ghostkeeper** [comment]
@zebons Sorry, I forgot to mention that it also needs the namespace definition at the top of the file in the `<fdmmaterial>` tag then:

    <fdmmaterial xmlns="http://www.ultimaker.com/material" xmlns:cura="http://www.ultimaker.com/cura" version="1.3">

**Comment by zebons** [comment]
@Ghostkeeper doesn;t work

**Comment by Ghostkeeper** [comment]
Like I said, the Flow parameter will not enter in the profile screen:

> However it still won't show up in the Cura interface. The list of settings there is hard-coded in Cura.

But it will change the setting when you load the material. The point of this is that you then don't need to override the setting in all of the quality profiles.

**Comment by zebons** [comment]
Ah Ok I undertstood the concept but as we cann't see the value in the profile material screen, not easy to manage it if we can only change it by editing the profile material file. 
By the way, we can use the MaterialSettingsPlugin and then see the choosen params in the profile screen

**Comment by trouch** [comment]
thanks again @Ghostkeeper for your support and keeping the mod essence upstream !
hope you're all safe at ultimaker !
