### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by drock1985** [trouch/CreawsomeMod#45]
Hi,

I see that the mod was updated to Beta 0.3 and I was wondering what the changes were between 0.2 and 0.3 versions?

Thanks,

**Comment by RFC1795** [comment]
For one, I see I'm now purging from the left side rather than the front. I also got some message pop-up when I started the new profile, I dismissed. Something about my firewall complaining about some setting, I dismissed that too. First print I had to cancel, I might go back to the previous release after a few more tries.

**Comment by 1aTa** [comment]
Just click on releases.

https://github.com/trouch/CreawsomeMod/releases/tag/20190527-0.3.0

**Comment by trouch** [comment]
> Just click on releases.
> 
> https://github.com/trouch/CreawsomeMod/releases/tag/20190527-0.3.0
